### ISSUE TITLE
Mensagens positivas pra quem usa a hashtag #CodandoJuntas

### ISSUE THREAD

**Issue by evelynstender** [CodandoJuntas/twitterbot#4]
**A solicitação está ligada a um problema? Descreva**
Não está ligada a nenhum problema, porém seria interessante a implementação de uma feature que manda mensagens positivas para as meninas que postam #CodandoJuntas no twitter.

**Descreva uma possível solução**
Pra implementar essa feature, precisamos de algumas frases padrões que serão usadas aleatóriamente cada vez que alguém tweeta a hashtag. Seria interessante as pessoas darem ideias das frases.

**Informações adicionais/Observações**
Comentem na Issue algumas frases de incentivo legais pra mandarmos pras meninas :)

**Comment by barretoana** [comment]
Será que não ia ficar muito flood TODA vez?
É possível fazer combinação com outras palavras chaves? Tipo se a pessoa falar "muito difícil" a resposta ser uma parada tipo ~mandando bits de good vibes~

**Comment by barretoana** [comment]
Tem muita gente usando #CodandoJuntas e #100DiasDeCodigo, talvez fosse legal fazer algo sobre isso também (não sei muito bem o que da pra ser feito, ai fica difícil rs)

**Comment by angolini** [comment]
Aconteceu uma coisa ontem no face. A moça pediu ajuda, eu fiz uma pergunta que ela nem entendeu a pergunta, aí ela falou pra mim "o que é x, pega leve comigo que eu estou começando".

Logo depois a moça começou o clássico discurso auto depreciativo no estilo "não vou conseguir", no que eu respondi: "pega leve com você, você está só começando".

Talvez o bot possa sair falando pras mulheres pegarem leve com elas próprias. Talvez a gente possa tentar identificar as palavras chaves do "discurso clássico auto depreciativo"

Outra frase que eu gosto bastante é "não compare o seu meio com o fim de outra pessoa". Ou variações dessa coisa de não se comparar com o outro, mas sim com o seu próprio passado.

Agora, um ponto que eu acho imprescindível é não sair falando "você é maravilhosa" "você é foda" você é incrível" porque isso de um bot vai parecer muito artificial, se já é artificial vindo de pessoas desconhecidas, imagina de um bot. Se for elogiar, vamos pensar em elogios menores e mais de professor pra aluninho.

**Comment by barretoana** [comment]
Gostei das ideias da Dai e concordo! Elogio vazio de bot é meh.

Acho que a gente pode ir mais pelo humor e frases motivacionais-não-toscas

**Comment by angolini** [comment]
Se é humor, manda uma foto de gatinho quando alguém estiver xingando muito

**Comment by angolini** [comment]
Quando alguém falar "essa merda não funciona" manda aquelas fotos de cachorro "mamae, o sofá explodiu, que bom que eu tô bem né?" (tô largada rindo disso)

**Comment by evelynstender** [comment]
Bem falado meninas. Eu também acho que aquelas mesmas frases repetitivas enchem o saco. A ideia de usar o humor que a @angolini citou é muito boa... Acho que da uma suavizada no clima hehe..
Talvez memes? Fotos de bichos fofos?

**Comment by angolini** [comment]
Como a gente faz pra sentir  (ou testar) pra ver como que o negócio tá fluindo? (manjo nada)

**Comment by evelynstender** [comment]
@angolini vc diz em relação a essa Issue? Se for, vou pensar melhor no decorrer da semana (ideias são sempre bem vindas) :P

**Comment by angolini** [comment]
Acho que eu quis dizer se dá pra rodar um _rascunho_ do bot antes de implementar efetivamente. Pra gente poder brincar com ele e sentir se tá assim ou assado.

Mas olha, eu não manjo nada! Se eu tiver falando groselha você me conta, plis

**Comment by evelynstender** [comment]
O Bot em si já está no ar dando RT na galera que posta a hashtag #CodandoJuntas: https://twitter.com/CodandoJuntsBot

O que da pra fazer pra testar um rascunho é criar uma outra conta qualquer no twitter e ir testando as coisas por lá e tal, mas não sei o quão viável é fazer isso

**Comment by angolini** [comment]
Eu sinceramente não sei o que esperar de um bot. Sei que tem que ser uma resposta pasteurizada (pra ficar com cara de bot e não de ficar pedante, minha humilde opinião que pode estar errada).

Mas o povo **hoje** usando a hashtag tá bastante monossilábico, achei um tuite só falando de passar raiva, a maioria vai a linha do contar um fato passado. "estudei tal coisa", "quero tal coisa", "comecei um curso x".

Eu vou me abster de dar mais ideia porque eu não sei opinar mais

**Comment by evelynstender** [comment]
Eu só fico pensando na dificuldade de conseguir distinguir os tweets de pessoas que estão reclamando ou começando algo ou fazendo alguma outra coisa... Eu realmente não pensei ainda sobre como isso poderia ser feito.
Talvez não seja a hora ainda pra esse esquema de mensagens pra galera. Talvez no futuro ou coisas assim. Talvez seria melhor mesmo pensar em coisas mais simples e ir avançando aos poucos (até pq acho que seria legal as meninas acompanharem o código do bot e se tiver coisa mto avançada logo de cara, pode ser que quem está começando não curta olhar ou até mesmo colaborar)

**Comment by evelynstender** [comment]
O que vcs acham de fechar essa Issue?

**Comment by angolini** [comment]
Oi, tem alguém aí? Algúem poderia, por favor, fechar esse issue?

**Comment by angolini** [comment]
@evelynstender , podemos, por favor, fechar essa issue?

**Comment by evelynstender** [comment]
@angolini fechando!
