### ISSUE TITLE
Licença para o bot

### ISSUE THREAD

**Issue by barretoana** [CodandoJuntas/twitterbot#5]
**A solicitação está ligada a um problema? Descreva**
Precisamos definir uma licença open source para esse projeto.

**Descreva uma possível solução**
A solução é obvia: escolher uma e atualizar o readme. 

**Descreva as alternativas que você considerou**
Eu realmente não entendo muito sobre, então deixo nas mãos de quem sabe mais.

**Informações adicionais/Observações**
Vocês são show.

**Comment by angolini** [comment]
Fiz uma pesquisa por outros bots de twitter escritos em javascript e a maioria é MIT.

MIT é uma licença boa porque garante vários direitos (inclusive comerciais) e não contamina código proprietário.

Por outro lado, alguém usando como base o código desse repositório poderá fechar o código e usar em uma ferramenta proprietária de uso comercial.

Mas eu não vejo isso como algo negativo, pense que será uma mulher que usará esse bot como base para seu cargo em alguma empresa.

Meu voto é **MIT**

Se alguém achar algum ponto da minha interpretação que esteja falha, por favor me ajude a melhorar, gostaria muito de saber!

**Comment by evelynstender** [comment]
Bem pensado @thepurpleana! Tinha passado pela minha cabeça isso de licença, mas eu não conheço muito como funciona também!
@angolini eu vou pesquisar sobre esse **MIT**. Qualquer dúvida, posso te perguntar?

**Comment by angolini** [comment]
@evelynstender, pode sim. Por favor vamos conversar!

Eu também estou no processo e principalmente, não sou advogada! Então nada do que eu disse é formal. Idealmente teríamos que consultar um advogado né? Mas a gente vai tocando.

Tente dar uma lida em outras licenças também, quem sabe você não se afeiçoa com outra.

**Comment by evelynstender** [comment]
@angolini talvez um advogado seja legal. Quem sabe não tenha alguém do CodandoJuntas que é advogada e gostaria de ajudar? Enquanto isso, vou ler como funciona esse esquema de licença! Se você achar mais alguma coisa interessante, manda pra nooooissss :D

**Comment by angolini** [comment]
Oi, tem alguém aí? Algúem poderia por favor, fechar esse issue?

**Comment by angolini** [comment]
Olá, @barretoana, poderia, por favor, fechar esse issue?

**Comment by evelynstender** [comment]
@angolini fechando!
